<a href="https://colab.research.google.com/github/25wh1a05f0-pixel/naascom/blob/main/EV_Battery_case.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Battery Sensor Data Analysis

In [5]:
import pandas as pd

# Battery sensor data from the description
data = {
    'Time (h)': [0, 1, 2, 3, 4, 5],
    'Temperature (°C)': [32, 35, 38, 40, 42, 45],
    'Voltage (V)': [400, 395, 390, 385, 380, 375],
    'Current (A)': [20, 22, 25, 28, 30, 32],
    'Charge (%)': [95, 88, 80, 70, 60, 48]
}

df_battery = pd.DataFrame(data)

# Display the DataFrame
display(df_battery)

   Time (h)  Temperature (°C)  Voltage (V)  Current (A)  Charge (%)
0         0                32          400           20          95
1         1                35          395           22          88
2         2                38          390           25          80
3         3                40          385           28          70
4         4                42          380           30          60
5         5                45          375           32          48

#Task 1: Analysis Using Python Basics

#### 1. Display the sensor readings using a for loop

In [10]:
print("Battery Sensor Readings:")
for index, row in df_battery.iterrows():
    print(f"Time: {row['Time (h)']}h, Temp: {row['Temperature (°C)']}°C, Voltage: {row['Voltage (V)']}V, Current: {row['Current (A)']}A, Charge: {row['Charge (%)']}% ")

Battery Sensor Readings:
Time: 0h, Temp: 32°C, Voltage: 400V, Current: 20A, Charge: 95%
Time: 1h, Temp: 35°C, Voltage: 395V, Current: 22A, Charge: 88%
Time: 2h, Temp: 38°C, Voltage: 390V, Current: 25A, Charge: 80%
Time: 3h, Temp: 40°C, Voltage: 385V, Current: 28A, Charge: 70%
Time: 4h, Temp: 42°C, Voltage: 380V, Current: 30A, Charge: 60%
Time: 5h, Temp: 45°C, Voltage: 375V, Current: 32A, Charge: 48%

#### 2. Identify high temperature

In [11]:
print("Temperature Status:")
for index, row in df_battery.iterrows():
    if row['Temperature (°C)'] > 40:
        print(f"Time {row['Time (h)']}h: High Temperature Alert ({row['Temperature (°C)']}°C)")
    else:
        print(f"Time {row['Time (h)']}h: Temperature Normal ({row['Temperature (°C)']}°C)")

Temperature Status:
Time 0h: Temperature Normal (32°C)
Time 1h: Temperature Normal (35°C)
Time 2h: Temperature Normal (38°C)
Time 3h: Temperature Normal (40°C)
Time 4h: High Temperature Alert (42°C)
Time 5h: High Temperature Alert (45°C)

#### 3. Identify low battery

In [12]:
print("Battery Charge Status:")
for index, row in df_battery.iterrows():
    if row['Charge (%)'] < 50:
        print(f"Time {row['Time (h)']}h: Low Battery Alert ({row['Charge (%)']}%) ")
    else:
        print(f"Time {row['Time (h)']}h: Battery Charge Normal ({row['Charge (%)']}%) ")

Battery Charge Status:
Time 0h: Battery Charge Normal (95%)
Time 1h: Battery Charge Normal (88%)
Time 2h: Battery Charge Normal (80%)
Time 3h: Battery Charge Normal (70%)
Time 4h: Battery Charge Normal (60%)
Time 5h: Low Battery Alert (48%)

#### 4. Create a function `battery_status(charge)`

In [13]:
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"

print("Battery Status using function:")
for index, row in df_battery.iterrows():
    status = battery_status(row['Charge (%)'])
    print(f"Time {row['Time (h)']}h: Charge {row['Charge (%)']}% - Status: {status}")

Battery Status using function:
Time 0h: Charge 95% - Status: High
Time 1h: Charge 88% - Status: High
Time 2h: Charge 80% - Status: High
Time 3h: Charge 70% - Status: Medium
Time 4h: Charge 60% - Status: Medium
Time 5h: Charge 48% - Status: Low

### Task 2: Analysis Using NumPy

In [14]:
import numpy as np

# Convert the relevant DataFrame columns to a NumPy array
# Excluding 'Time (h)' as per the matrix D in the prompt
battery_data_np = df_battery[['Temperature (°C)', 'Voltage (V)', 'Current (A)', 'Charge (%)']].to_numpy()
display(battery_data_np)

array([[ 32, 400,  20,  95],
       [ 35, 395,  22,  88],
       [ 38, 390,  25,  80],
       [ 40, 385,  28,  70],
       [ 42, 380,  30,  60],
       [ 45, 375,  32,  48]])

#### 1. Find the shape of the array

In [21]:
array_shape = battery_data_np.shape
print(f"Shape of the array (rows, columns): {array_shape}")

Shape of the array (rows, columns): (6, 4)

#### 2. Calculate the average of each parameter

In [16]:
average_parameters = np.mean(battery_data_np, axis=0)
print(f"Average Temperature: {average_parameters[0]:.2f}°C")
print(f"Average Voltage: {average_parameters[1]:.2f}V")
print(f"Average Current: {average_parameters[2]:.2f}A")
print(f"Average Charge: {average_parameters[3]:.2f}%")

Average Temperature: 38.67°C
Average Voltage: 387.50V
Average Current: 26.17A
Average Charge: 73.50%

#### 3. Find the maximum and minimum temperature

In [17]:
max_temp = np.max(battery_data_np[:, 0])
min_temp = np.min(battery_data_np[:, 0])
print(f"Maximum Temperature: {max_temp}°C")
print(f"Minimum Temperature: {min_temp}°C")

Maximum Temperature: 45°C
Minimum Temperature: 32°C

#### 4. Extract the voltage column

In [18]:
voltage_column = battery_data_np[:, 1]
display(voltage_column)

array([400, 395, 390, 385, 380, 375])

#### 5. Identify high-temperature readings (T > 40 °C)

In [19]:
high_temp_readings = battery_data_np[battery_data_np[:, 0] > 40]
print("High Temperature Readings (T > 40 °C):")
display(high_temp_readings)

High Temperature Readings (T > 40 °C):

array([[ 42, 380,  30,  60],
       [ 45, 375,  32,  48]])

#### 6. Identify low battery readings (C < 50 %)

In [22]:
low_battery_readings = battery_data_np[battery_data_np[:, 3] < 50]
print("Low Battery Readings (C < 50 %):")
display(low_battery_readings)

Low Battery Readings (C < 50 %):

array([[ 45, 375,  32,  48]])

### Task 3: Analysis Using Linear Algebra

In [28]:
import numpy as np

A = np.array([[2, 1], [1, 3]])
X = np.array([[40], [25]])

Y = np.dot(A, X)
print("Resulting vector Y (Battery Stress Index):")
display(Y)

Resulting vector Y (Battery Stress Index):

array([[105],
       [115]])

#### 1. Transpose of A (Aᵀ)

In [29]:
A_transpose = A.T
print("Transpose of A (Aᵀ):")
display(A_transpose)

Transpose of A (Aᵀ):

array([[2, 1],
       [1, 3]])

#### 2. Determinant of A (det(A))

In [30]:
A_determinant = np.linalg.det(A)
print(f"Determinant of A (det(A)): {A_determinant}")

Determinant of A (det(A)): 5.000000000000001

#### 3. Inverse of A (A⁻¹)

In [31]:
try:
    A_inverse = np.linalg.inv(A)
    print("Inverse of A (A⁻¹):")
    display(A_inverse)
except np.linalg.LinAlgError:
    print("Inverse does not exist for matrix A.")

Inverse of A (A⁻¹):

array([[ 0.6, -0.2],
       [-0.2,  0.4]])

#### Solving a System of Equations

In [32]:
A_system = np.array([[2, 1], [1, 3]])
B_system = np.array([100, 120])

solution = np.linalg.solve(A_system, B_system)

print(f"Solution for x: {solution[0]:.2f}")
print(f"Solution for y: {solution[1]:.2f}")

Solution for x: 36.00
Solution for y: 28.00

### Task 4: Analysis Using Calculus

#### 1. Find the rate of change of battery charge

In [33]:
def C_t(t):
    return 100 - 2 * t - 0.5 * t**2

def dC_dt(t):
    return -2 - t

print("Battery charge function: C(t) = 100 - 2t - ½t²")
print("Rate of change of battery charge: dC/dt = -2 - t")

Battery charge function: C(t) = 100 - 2t - ½t²
Rate of change of battery charge: dC/dt = -2 - t

#### 2. Calculate the discharge rate

In [34]:
discharge_rate_t2 = dC_dt(2)
discharge_rate_t5 = dC_dt(5)

print(f"Discharge rate at t = 2 hours (dC/dt): {discharge_rate_t2} %/h")
print(f"Discharge rate at t = 5 hours (dC/dt): {discharge_rate_t5} %/h")

Discharge rate at t = 2 hours (dC/dt): -4 %/h
Discharge rate at t = 5 hours (dC/dt): -7 %/h

#### 3. Interpret the result

In [37]:
if discharge_rate_t2 < discharge_rate_t5:
    interpretation = "The battery is losing charge at an increasing rate."
elif discharge_rate_t2 > discharge_rate_t5:
    interpretation = "The battery is losing charge at a decreasing rate."
else:
    interpretation = "The battery is losing charge at a constant rate."

print(interpretation)
print("Since the derivative dC/dt = -2 - t, as 't' increases, dC/dt becomes more negative, indicating an increasing rate of discharge.")

The battery is losing charge at a decreasing rate.
Since the derivative dC/dt = -2 - t, as 't' increases, dC/dt becomes more negative, indicating an increasing rate of discharge.

### Generated Dataset for Calculus Analysis

In [38]:
import pandas as pd
import numpy as np

time_points = np.arange(0, 6, 1)

charge_values = [C_t(t) for t in time_points]
discharge_rates = [dC_dt(t) for t in time_points]

calculus_df = pd.DataFrame({
    'Time (h)': time_points,
    'Charge C(t) (%)': charge_values,
    'dC/dt (%/h)': discharge_rates
})

display(calculus_df)

   Time (h)  Charge C(t) (%)  dC/dt (%/h)
0         0            100.0           -2
1         1             97.5           -3
2         2             94.0           -4
3         3             89.5           -5
4         4             84.0           -6
5         5             77.5           -7

### Final Analysis and Decision - Battery Performance Report

#### 1. Safety: At what time does the temperature first exceed 40 °C?

In [50]:
first_high_temp_time = df_battery[df_battery['Temperature (°C)'] > 40]['Time (h)'].min()
print(f"The temperature first exceeds 40 °C at {first_high_temp_time} hours.")

The temperature first exceeds 40 °C at 4 hours.

#### 2. Battery Charge: Calculate the total charge reduction (Charge Loss = C_initial − C_final)

In [49]:
initial_charge = df_battery['Charge (%)'].iloc[0]
final_charge = df_battery['Charge (%)'].iloc[-1]
charge_loss = initial_charge - final_charge
print(f"Initial Charge: {initial_charge}%")
print(f"Final Charge: {final_charge}%")
print(f"Total Charge Reduction (Charge Loss): {charge_loss}%")

Initial Charge: 95%
Final Charge: 48%
Total Charge Reduction (Charge Loss): 47%

#### 3. NumPy Analysis: Calculate T̄, V̄, Ī, and C̄.

In [48]:
print(f"Average Temperature (T̄): {average_parameters[0]:.2f}°C")
print(f"Average Voltage (V̄): {average_parameters[1]:.2f}V")
print(f"Average Current (Ī): {average_parameters[2]:.2f}A")
print(f"Average Charge (C̄): {average_parameters[3]:.2f}%")

Average Temperature (T̄): 38.67°C
Average Voltage (V̄): 387.50V
Average Current (Ī): 26.17A
Average Charge (C̄): 73.50%

#### 4. Linear Algebra: Calculate the transformed output Y = AX, and solve AX = B.

In [47]:
print("Transformed output Y (Battery Stress Index) = AX:")
display(Y)
print(f"Solution for AX = B: x = {solution[0]:.2f}, y = {solution[1]:.2f}")

Transformed output Y (Battery Stress Index) = AX:

array([[105],
       [115]])

Solution for AX = B: x = 36.00, y = 28.00

#### 5. Calculus: Analyze the rate of battery discharge using dC/dt.

In [46]:
print("From the calculus analysis (dC/dt = -2 - t), as time increases, the discharge rate becomes more negative.")
print("This indicates that the battery is losing charge at an increasing rate.")
print("For example, dC/dt at t=2h is -4%/h, and at t=5h is -7%/h.")

From the calculus analysis (dC/dt = -2 - t), as time increases, the discharge rate becomes more negative.
This indicates that the battery is losing charge at an increasing rate.
For example, dC/dt at t=2h is -4%/h, and at t=5h is -7%/h.

#### 6. Final Decision: Based on the analysis, select one of the following:
*   APPROVE — The battery is operating safely.
*   MONITOR — The battery requires continuous monitoring.
*   REJECT — The battery shows unsafe operating conditions.

In [45]:
final_decision = "MONITOR"
reasons = []

if first_high_temp_time is not None and first_high_temp_time < 5:
    reasons.append(f"Temperature exceeds 40 °C starting at {first_high_temp_time} hours, indicating potential overheating.")

if final_charge < 50:
    reasons.append(f"Battery charge drops below 50% (final charge {final_charge}%), indicating significant discharge.")

if 'increasing rate' in interpretation.lower():
    reasons.append("Calculus analysis shows the battery is discharging at an increasing rate, which is a concern for efficiency and longevity.")


if not reasons:
    final_decision = "APPROVE"
    reasons.append("All parameters are within acceptable limits.")
elif len(reasons) > 2:
    final_decision = "REJECT"


print(f"Final Decision: {final_decision}")
print("Reasons:")
for reason in reasons:
    print(f"- {reason}")

Final Decision: MONITOR
Reasons:
- Temperature exceeds 40 °C starting at 4 hours, indicating potential overheating.
- Battery charge drops below 50% (final charge 48%), indicating significant discharge.